import type { Accessory, Business, BusinessType, Category, EcoAlternative, PackagingBox, PackagingGuide, PackagingMaterial, Supplier } from "@/types";

// Image mapping for different packaging types and business categories
function getImageUrl(productType: string, category: string): string {
  const imageMap: Record<string, string> = {
    // Kraft/Eco packaging
    "Kraft Mailer": "https://images.unsplash.com/photo-1596532212624-088ff6d50dde?auto=format&fit=crop&w=900&q=80",
    "Corrugated Box": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",
    
    // Wrapping and tissue
    "Tissue Paper": "https://images.unsplash.com/photo-1532619675605-1ede6c2e2fe0?auto=format&fit=crop&w=900&q=80",
    "Silk Ribbon": "https://images.unsplash.com/photo-1596532212624-088ff6d50dde?auto=format&fit=crop&w=900&q=80",
    
    // Protective packaging
    "Bubble Wrap": "https://images.unsplash.com/photo-1596788978022-0ad0b7fa6835?auto=format&fit=crop&w=900&q=80",
    "Eco Paper Tape": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",
    
    // Luxury/Premium
    "Velvet Pouch": "https://images.unsplash.com/photo-1535497261174-af66b18d9e2d?auto=format&fit=crop&w=900&q=80",
    "Jewellery Box": "https://images.unsplash.com/photo-1515929304392-cc6b2e52b53f?auto=format&fit=crop&w=900&q=80",
    
    // Branding/Labels
    "Thank You Card": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?auto=format&fit=crop&w=900&q=80",
    "Brand Sticker": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?auto=format&fit=crop&w=900&q=80",
    
    // Food/Bakery
    "Cake Box": "https://images.unsplash.com/photo-1578500494198-246f612d03b3?auto=format&fit=crop&w=900&q=80",
    "Food Safe Box": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",
    
    // Premium boxes
    "Premium Box": "https://images.unsplash.com/photo-1532619675605-1ede6c2e2fe0?auto=format&fit=crop&w=900&q=80",
    "Window Box": "https://images.unsplash.com/photo-1596532212624-088ff6d50dde?auto=format&fit=crop&w=900&q=80",
    "Candle Box": "https://images.unsplash.com/photo-1596788978022-0ad0b7fa6835?auto=format&fit=crop&w=900&q=80",
    "Soap Sleeve": "https://images.unsplash.com/photo-1532619675605-1ede6c2e2fe0?auto=format&fit=crop&w=900&q=80",
    
    // Accessories
    "Foam Insert": "https://images.unsplash.com/photo-1596788978022-0ad0b7fa6835?auto=format&fit=crop&w=900&q=80",
  };
  
  return imageMap[productType] || "https://images.unsplash.com/photo-1596532212624-088ff6d50dde?auto=format&fit=crop&w=900&q=80";
}

const businessTypes = [
  "Crochet",
  "Bakery",
  "Jewellery",
  "Candles",
  "Handmade Soap",
  "Clothing",
  "Chocolates",
  "Rakhi",
  "Gift Products",
  "Pottery",
  "Handmade Crafts",
  "Home Decor",
  "Cosmetics",
  "Stationery",
  "Handmade Accessories",
] as const;

export const categories: Category[] = [
  { id: "craft", name: "Craft", description: "For handmade and artistic goods", icon: "🎨" },
  { id: "bakery", name: "Bakery", description: "Fresh and premium food packaging", icon: "🥐" },
  { id: "jewellery", name: "Jewellery", description: "Luxury presentation for small gift items", icon: "💍" },
  { id: "candle", name: "Candles", description: "Protective packaging for wax and glass", icon: "🕯️" },
  { id: "soap", name: "Handmade Soap", description: "Natural packaging for artisanal soap bars", icon: "🧼" },
  { id: "fashion", name: "Clothing", description: "Boutique packaging for apparel and accessories", icon: "👗" },
  { id: "chocolate", name: "Chocolates", description: "Food-safe gift packaging for sweets", icon: "🍫" },
  { id: "rakhi", name: "Rakhi", description: "Festive packaging for traditional gifts", icon: "🎁" },
  { id: "gift", name: "Gift Products", description: "Premium wrapping for curated gifts", icon: "🎀" },
  { id: "pottery", name: "Pottery", description: "Cushioned packaging for fragile ceramic goods", icon: "🏺" },
  { id: "decor", name: "Home Decor", description: "Presentation for decorative items", icon: "🪴" },
  { id: "cosmetics", name: "Cosmetics", description: "Elegant packaging for beauty products", icon: "💄" },
  { id: "stationery", name: "Stationery", description: "Organized packaging for paper goods", icon: "✉️" },
  { id: "accessories", name: "Accessories", description: "Finishing touches for created accessories", icon: "🧵" },
  { id: "premium", name: "Premium", description: "High-end packaging options", icon: "✨" },
];

const businessSections = ["Package Builder", "Collaboration", "Supplier Matches"] as const;

export const businesses: Business[] = [
  { id: "b1", name: "Aarav Crochet Studio", businessType: "Crochet", description: "Handmade crochet accessories designed for gifting.", imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80", category: "Craft", tags: ["handmade", "gift-ready"], section: "Collaboration", email: "hello@aaravcrochet.com", phone: "+91-98765-43210", website: "www.aaravcrochet.com", pricing: { minOrder: 500, currency: "INR", priceRange: "₹200-500 per piece" } },
  { id: "b2", name: "Mira Bakery House", businessType: "Bakery", description: "Artisan cakes and pastries that need fresh-safe packaging.", imageUrl: "https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?auto=format&fit=crop&w=800&q=80", category: "Bakery", tags: ["fresh", "food-safe"], section: "Package Builder", email: "contact@mirabakery.com" },
  { id: "b3", name: "Luna Candle Co.", businessType: "Candles", description: "Luxury candles with eco-aware packaging solutions.", imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80", category: "Candles", tags: ["luxury", "sustainable"] },
  { id: "b4", name: "Rakhi Royale", businessType: "Rakhi", description: "Traditional gift presentation for festival gifting.", imageUrl: "https://images.unsplash.com/photo-1598974357801-cbca4c8b3f8c?auto=format&fit=crop&w=800&q=80", category: "Rakhi", tags: ["festival", "premium"] },
  { id: "b5", name: "Silk Route Jewellery", businessType: "Jewellery", description: "Handcrafted jewellery with bespoke premium packaging.", imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80", category: "Jewellery", tags: ["luxury", "presentation"] },
  { id: "b6", name: "Bloom Soapery", businessType: "Handmade Soap", description: "Natural soap bars packaged for boutique retail.", imageUrl: "https://images.unsplash.com/photo-1511285560929-64654b3bb0a0?auto=format&fit=crop&w=800&q=80", category: "Handmade Soap", tags: ["natural", "artisanal"] },
  { id: "b7", name: "Threaded Wardrobe", businessType: "Clothing", description: "Boutique apparel packaging for premium brands.", imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80", category: "Clothing", tags: ["fashion", "retail"] },
  { id: "b8", name: "Choco Craft", businessType: "Chocolates", description: "Gourmet chocolate packaging built for gifting and delivery.", imageUrl: "https://images.unsplash.com/photo-1542258160-0bcb5d6a2f9f?auto=format&fit=crop&w=800&q=80", category: "Chocolates", tags: ["food-safe", "gift"] },
  { id: "b9", name: "Potter's Loft", businessType: "Pottery", description: "Handmade ceramics requiring protective, premium packaging.", imageUrl: "https://images.unsplash.com/photo-1475688621402-4257f74d8b06?auto=format&fit=crop&w=800&q=80", category: "Pottery", tags: ["fragile", "protective"] },
  { id: "b10", name: "Green Decor Studio", businessType: "Home Decor", description: "Decor items that need elegant and secure packaging.", imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80", category: "Home Decor", tags: ["stylish", "safe"] },
  { id: "b11", name: "Velvet Charm", businessType: "Handmade Accessories", description: "Accessories with curated packaging for small luxury brands.", imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80", category: "Handmade Accessories", tags: ["gift", "premium"] },
  { id: "b12", name: "Paper & Ink", businessType: "Stationery", description: "Designer stationery that benefits from crisp presentation packaging.", imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80", category: "Stationery", tags: ["organized", "premium"] },
  { id: "b13", name: "Glow Cosmetics", businessType: "Cosmetics", description: "Beauty products packaged for retail and gifting.", imageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80", category: "Cosmetics", tags: ["luxury", "brandable"] },
  { id: "b14", name: "Studio Giftworks", businessType: "Gift Products", description: "Curated gift products with premium packaging finish.", imageUrl: "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?auto=format&fit=crop&w=800&q=80", category: "Gift Products", tags: ["curated", "presentable"] },
];

for (let i = 0; i < 36; i += 1) {
  businesses.push({
    id: `b${i + 15}`,
    name: `${["Studio", "Collective", "Works", "Boutique", "Designs"][i % 5]} ${businessTypes[i % businessTypes.length]}`,
    businessType: businessTypes[i % businessTypes.length],
    description: "Small business packaging needs aligned to premium product presentation.",
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80",
    category: categories[i % categories.length].name,
    tags: ["premium", "branding"],
    section: businessSections[i % businessSections.length],
  });
}

const supplierNames = [
  "PackHub Studio",
  "EcoBox Supply",
  "Artisan Packs",
  "FreshWrap Systems",
  "Luxury Label Co.",
  "SafeShip Solutions",
  "Craft Pack Partners",
  "FoodSafe Packaging",
  "Custom Fold",
  "Green Wraps",
  "BufferBox Labs",
  "Velvet Packaging",
  "Paper Song",
  "GlassGuard Supplies",
  "Ribbon & Rope",
  "Pearl Packaging",
];

export const suppliers: Supplier[] = supplierNames.map((name, index) => ({
  id: `sup-${index + 1}`,
  name,
  category: categories[index % categories.length].name,
  imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80",
  rating: 4 + (index % 5) * 0.1,
  location: ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Ahmedabad"][index % 5],
  leadTime: `${2 + (index % 4)} days`,
  specialties: ["eco packaging", "custom branding", "bulk orders", "food-safe", "fragile shipping"].slice(0, 3),
  businessTypes: [businessTypes[index % businessTypes.length], businessTypes[(index + 1) % businessTypes.length]],
}));

const materialTemplates = [
  {
    name: "Food-Safe Kraft Paper",
    purpose: "Bakery wrap and liner",
    description: "Food-safe kraft paper that works for pastry wraps, sandwich sleeves, and bakery display liners.",
    bestFor: "Bakery, pastries, cafe quick service",
    advantages: ["Food-safe", "Sustainable", "Easy to print"],
    disadvantages: ["Needs additional coating for wet items"],
    tags: ["bakery", "food-safe", "kraft"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Greaseproof Paper",
    purpose: "Freshness barrier for baked goods",
    description: "Greaseproof paper protects buns, cookies, and sweets from oil absorption while keeping the finish clean.",
    bestFor: "Bakery, confectionery, takeaway food",
    advantages: ["Grease-resistant", "Lightweight", "Affordable"],
    disadvantages: ["Less rigid for shipping"],
    tags: ["bakery", "food-safe", "liners"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Butter Paper",
    purpose: "Bakery wrap and tray layer",
    description: "Soft paper sheets used to line trays and wrap baked items without excess moisture.",
    bestFor: "Cookies, muffins, pastries, breads",
    advantages: ["Good moisture control", "Cost-effective"],
    disadvantages: ["Not suitable for bulky shipping"],
    tags: ["bakery", "tray liner", "paper"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Kraft Mailer",
    purpose: "Lightweight shipping wrap",
    description: "A durable kraft mailer for crochet items, accessories, and light handmade goods shipped directly to customers.",
    bestFor: "Crochet, handmade accessories, apparel",
    advantages: ["Strong enough for light goods", "Eco-conscious", "Branded-ready"],
    disadvantages: ["Not intended for heavy or sharp items"],
    tags: ["crochet", "mailer", "shipping"],
    businessType: "Crochet",
    category: "Craft",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Honeycomb Wrap",
    purpose: "Protective wrap for soft crafts",
    description: "A cushioning wrap that protects handmade pieces and keeps them from being crushed in transit.",
    bestFor: "Crochet, handmade gift sets, soft craft goods",
    advantages: ["Good cushioning", "Lightweight", "Recyclable"],
    disadvantages: ["Bulkier than tissue wrap"],
    tags: ["crochet", "protective", "wrap"],
    businessType: "Crochet",
    category: "Craft",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Paper Sleeve",
    purpose: "Retail sleeve for handmade products",
    description: "Simple paper sleeves add a premium finish to small craft and accessory items while keeping costs low.",
    bestFor: "Crochet bundles, gift sets, small accessories",
    advantages: ["Low cost", "Premium look", "Fast to ship"],
    disadvantages: ["Lower protection than rigid packaging"],
    tags: ["craft", "presentation", "retail"],
    businessType: "Crochet",
    category: "Craft",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Garment Sleeve",
    purpose: "Protective sleeve for folded clothing",
    description: "A breathable garment sleeve designed to protect apparel while keeping the presentation clean and premium.",
    bestFor: "Apparel, shirts, dresses, boutique fashion",
    advantages: ["Protective", "Brandable", "Lightweight"],
    disadvantages: ["Not for heavy or wet garments"],
    tags: ["fashion", "garment", "protective"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Recycled Protective Wrap",
    purpose: "Cushioned wrap for apparel shipping",
    description: "Recycled paper wrap used to cushion folded garments and reduce void fill in apparel deliveries.",
    bestFor: "Clothing, shipping orders, gift bundles",
    advantages: ["Eco-conscious", "Cost-effective", "Good padding"],
    disadvantages: ["Needs an outer carton for heavier items"],
    tags: ["fashion", "shipping", "recycled"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Soap Sleeve",
    purpose: "Bar soap retail wrap",
    description: "A natural paper sleeve sized for handmade soap bars and boutique gifting packs.",
    bestFor: "Handmade soaps, gift bars, artisan retail",
    advantages: ["Natural finish", "Low cost", "Suitable for branding"],
    disadvantages: ["Less protective for very wet bars"],
    tags: ["soap", "retail", "wrap"],
    businessType: "Handmade Soap",
    category: "Handmade Soap",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Kraft Soap Box Material",
    purpose: "Box board for soap sets",
    description: "A rigid kraft board designed for small soap gift boxes and premium retail trays.",
    bestFor: "Handmade soap sets, gifting, boutique soaps",
    advantages: ["Strong structure", "Premium neutral finish", "Print-ready"],
    disadvantages: ["Not suited for very bulky products"],
    tags: ["soap", "kraft", "gift"],
    businessType: "Handmade Soap",
    category: "Handmade Soap",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Rigid Board",
    purpose: "Base material for jewellery presentation",
    description: "A sturdy rigid board that supports premium jewellery packaging and keeps delicate pieces stable.",
    bestFor: "Jewellery, gifting, premium small products",
    advantages: ["Strong structure", "Premium finish", "Protective"],
    disadvantages: ["Higher cost than paperboard"],
    tags: ["jewellery", "rigid", "presentation"],
    businessType: "Jewellery",
    category: "Jewellery",
    ecoFriendly: false,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Velvet Pouch Material",
    purpose: "Luxury presentation insert",
    description: "Soft pouch material designed to add a premium feel to jewellery and gifting sets.",
    bestFor: "Jewellery, rings, pendants, keepsakes",
    advantages: ["Luxurious finish", "Reusable", "Gift-ready"],
    disadvantages: ["Not a rigid protective shell"],
    tags: ["jewellery", "luxury", "pouch"],
    businessType: "Jewellery",
    category: "Jewellery",
    ecoFriendly: false,
    reusable: true,
    recyclable: false,
  },
  {
    name: "Jewellery Box Board",
    purpose: "Box structure for premium pieces",
    description: "Stiff board designed to create a premium jewellery box with enough structure for gifting and protection.",
    bestFor: "Jewellery boxes, gift trays, luxe presentation",
    advantages: ["Premium look", "Secure structure", "Customizable"],
    disadvantages: ["Higher unit cost"],
    tags: ["jewellery", "gifting", "premium"],
    businessType: "Jewellery",
    category: "Jewellery",
    ecoFriendly: false,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Food-Safe Wrapper",
    purpose: "Chocolate wrap and sleeve",
    description: "Food-safe wrapper built for chocolates, truffles, and small confectionery items.",
    bestFor: "Chocolates, sweets, confectionery",
    advantages: ["Food-safe", "Clean finish", "Good printability"],
    disadvantages: ["Limited structural protection"],
    tags: ["chocolate", "food-safe", "wrapper"],
    businessType: "Chocolates",
    category: "Chocolates",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Foil Wrapping",
    purpose: "Premium chocolate protection",
    description: "A foil wrap used to preserve flavour while giving premium confectionery a polished finish.",
    bestFor: "Chocolates, premium gift assortments",
    advantages: ["Excellent barrier", "Premium appearance", "Protects freshness"],
    disadvantages: ["Not always recyclable depending on laminate"],
    tags: ["chocolate", "foil", "premium"],
    businessType: "Chocolates",
    category: "Chocolates",
    ecoFriendly: false,
    reusable: false,
    recyclable: false,
  },
  {
    name: "Chocolate Box Material",
    purpose: "Box board for gifting and retail",
    description: "Sturdy box material created for chocolate gift boxes and premium assortment packs.",
    bestFor: "Chocolate boxes, gifting sets, truffles",
    advantages: ["Strong support", "Gift-ready look", "Print-friendly"],
    disadvantages: ["Heavier than wrap-only packaging"],
    tags: ["chocolate", "box", "premium"],
    businessType: "Chocolates",
    category: "Chocolates",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Candle Box Board",
    purpose: "Box construction for scented items",
    description: "Rigid board used for candle cartons and vessel packaging with a clean, premium appearance.",
    bestFor: "Candles, vessel candles, gift candle sets",
    advantages: ["Protective", "Retail-ready", "Customizable"],
    disadvantages: ["Requires internal support for glass"],
    tags: ["candles", "box", "retail"],
    businessType: "Candles",
    category: "Candles",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Wax Paper Liner",
    purpose: "Protective insert for candle vessels",
    description: "Wax paper lining helps protect melting wax and keeps containers neat during shipping and display.",
    bestFor: "Candles, wax products, gift sets",
    advantages: ["Protective", "Low cost", "Clean presentation"],
    disadvantages: ["Not for long-term wet storage"],
    tags: ["candles", "wax", "liner"],
    businessType: "Candles",
    category: "Candles",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Festive Mailer",
    purpose: "Rakhi shipping wrap",
    description: "A festive mailer designed to protect rakhi sets while feeling celebratory and premium.",
    bestFor: "Rakhi gifts, festival bundles, curated sets",
    advantages: ["Gift-ready", "Protective", "Festive feel"],
    disadvantages: ["Best for smaller orders"],
    tags: ["rakhi", "festive", "mailer"],
    businessType: "Rakhi",
    category: "Rakhi",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Decorative Box Board",
    purpose: "Gift-ready base for festival packaging",
    description: "Strong box board designed for rakhi and festival gift boxes that need both beauty and structure.",
    bestFor: "Rakhi, festive gifts, premium gifting",
    advantages: ["Strong structure", "Premium presentation", "Gift-ready"],
    disadvantages: ["Higher cost than simple mailers"],
    tags: ["rakhi", "gifting", "premium"],
    businessType: "Rakhi",
    category: "Rakhi",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Bubble Wrap",
    purpose: "Protection for fragile items",
    description: "Cushioning wrap used for fragile products and breakable items that need extra care during shipping.",
    bestFor: "Glass, ceramics, fragile goods",
    advantages: ["Shock absorbent", "Reusable", "Reliable"],
    disadvantages: ["Not as eco-friendly as paper alternatives"],
    tags: ["protection", "fragile", "shipping"],
    businessType: "General",
    category: "General",
    ecoFriendly: false,
    reusable: true,
    recyclable: false,
  },
  {
    name: "Paperboard",
    purpose: "General lightweight box material",
    description: "A versatile paperboard material used for boxes, sleeves, and packaging inserts across many product types.",
    bestFor: "General packaging, product inserts, lightweight boxes",
    advantages: ["Affordable", "Low weight", "Easy to print"],
    disadvantages: ["Less protective for heavy goods"],
    tags: ["general", "paperboard", "boxes"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
];

export const materials: PackagingMaterial[] = materialTemplates.map((template, index) => {
  const supplier = suppliers[(index + 1) % suppliers.length];
  const price =
    template.businessType === "Bakery" ? 140 + index * 12 :
    template.businessType === "Crochet" ? 110 + index * 10 :
    template.businessType === "Jewellery" ? 180 + index * 15 :
    template.businessType === "Chocolates" ? 160 + index * 12 :
    template.businessType === "Candles" ? 150 + index * 13 :
    template.businessType === "Rakhi" ? 130 + index * 11 : 120 + index * 9;

  return {
    id: `mat-${index + 1}`,
    name: template.name,
    imageUrl: getImageUrl(template.name, template.category),
    purpose: template.purpose,
    description: template.description,
    businessTypes: [template.businessType as BusinessType],
    category: template.category,
    price,
    currency: "INR",
    minimumOrderQuantity: `${20 + (index % 5) * 10} units`,
    supplier: supplier.name,
    supplierId: supplier.id,
    tags: template.tags,
    ecoFriendly: template.ecoFriendly,
    reusable: template.reusable,
    recyclable: template.recyclable,
    fragileSupport: template.name.includes("Wrap") || template.name.includes("Board") || template.name.includes("Box"),
    waterproof: template.name.includes("Paper") || template.name.includes("Wrap"),
    bestFor: template.bestFor,
    advantages: template.advantages,
    disadvantages: index % 2 === 0 ? ["Needs careful handling during storage"] : ["Best for moderate-weight goods"],
    availability: index % 3 === 0 ? "In stock" : index % 3 === 1 ? "Limited" : "Pre-order",
  };
});

const boxTemplates = [
  {
    name: "Cake Box",
    purpose: "Bakery display and protection",
    description: "A premium bakery box designed to keep cakes stable and presentable during transit and gifting.",
    bestFor: "Cakes, celebration desserts, pastry gifting",
    advantages: ["Food-safe", "Good structural support", "Print-ready"],
    disadvantages: ["Needs extra lining for very soft cakes"],
    tags: ["bakery", "cake", "premium"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Window Bakery Box",
    purpose: "Showcase bakery items",
    description: "A bakery box with a clear panel that highlights pastries or desserts while keeping them secure.",
    bestFor: "Cupcakes, pastries, cookies",
    advantages: ["Strong visual appeal", "Good product visibility"],
    disadvantages: ["Best for lighter items"],
    tags: ["bakery", "display", "window"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Kraft Mailer Box",
    purpose: "Crochet and craft shipping box",
    description: "A compact kraft mailer box that ships handmade items without oversized packaging waste.",
    bestFor: "Crochet kits, handcrafted gifts, small goods",
    advantages: ["Lightweight", "Brandable", "Affordable"],
    disadvantages: ["Not for heavy goods"],
    tags: ["craft", "shipping", "mailer"],
    businessType: "Crochet",
    category: "Craft",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Jewellery Rigid Box",
    purpose: "Premium jewellery display",
    description: "A structured rigid box for jewellery gifting, presentation, and safe storage.",
    bestFor: "Rings, bracelets, premium jewellery sets",
    advantages: ["Premium finish", "Strong protection", "Gift-ready"],
    disadvantages: ["Higher cost"],
    tags: ["jewellery", "luxury", "rigid"],
    businessType: "Jewellery",
    category: "Jewellery",
    ecoFriendly: false,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Chocolate Gift Box",
    purpose: "Confectionery presentation",
    description: "A premium chocolate box designed to hold assortment packs and keep the unboxing experience elegant.",
    bestFor: "Truffles, assortments, gift boxes",
    advantages: ["Strong packaging", "Premium look", "Food-safe options"],
    disadvantages: ["Larger footprint"],
    tags: ["chocolate", "gift", "premium"],
    businessType: "Chocolates",
    category: "Chocolates",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Candle Vessel Box",
    purpose: "Protective box for candle sets",
    description: "A sturdy candle box that secures glass and vessel candles without compromising presentation.",
    bestFor: "Candles, gift candle sets, vessel products",
    advantages: ["Secure fit", "Retail-ready", "Protective"],
    disadvantages: ["Requires careful insert placement"],
    tags: ["candles", "vessel", "gift"],
    businessType: "Candles",
    category: "Candles",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Rakhi Gift Box",
    purpose: "Festival gifting presentation",
    description: "A festive rakhi box built for premium gifting and safe presentation at weddings and celebrations.",
    bestFor: "Rakhi sets, festive gifting, curated combos",
    advantages: ["Celebratory look", "Strong structure", "Gift ready"],
    disadvantages: ["Bulky for very small orders"],
    tags: ["rakhi", "festival", "gift"],
    businessType: "Rakhi",
    category: "Rakhi",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Apparel Mailer",
    purpose: "Shipping packaging for clothing",
    description: "A compact mailer designed for garments and boutique apparel shipments that need a low-profile outer pack.",
    bestFor: "Apparel, shirts, dresses, fashion gifting",
    advantages: ["Lightweight", "Brandable", "Shipping-ready"],
    disadvantages: ["Extra cushioning helps with heavy garments"],
    tags: ["fashion", "mailing", "shipping"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Kraft Apparel Box",
    purpose: "Premium box for fashion presentation",
    description: "A structured kraft box for apparel gifting and premium retail packaging with a clean boutique finish.",
    bestFor: "Premium fashion, small wardrobes, gift sets",
    advantages: ["Premium look", "Good structure", "Strong branding"],
    disadvantages: ["Higher cost than mailers"],
    tags: ["fashion", "gift", "premium"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Soap Gift Box",
    purpose: "Gift-ready box for handmade soaps",
    description: "A compact retail box that gives artisan soaps a premium boutique presentation and protects them in transit.",
    bestFor: "Handmade soaps, gifting sets, natural products",
    advantages: ["Gift-ready", "Good protection", "Easy to brand"],
    disadvantages: ["Slightly larger footprint"],
    tags: ["soap", "gift", "retail"],
    businessType: "Handmade Soap",
    category: "Handmade Soap",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
  {
    name: "Premium Sleeve Box",
    purpose: "General premium packaging",
    description: "A classic premium sleeve box for gifting and retail presentation across many small-business products.",
    bestFor: "Accessories, cosmetics, small gifts",
    advantages: ["Stylish finish", "Compact", "Brandable"],
    disadvantages: ["Lower protection than rigid boxes"],
    tags: ["general", "premium", "gift"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: true,
    recyclable: true,
  },
];

export const boxes: PackagingBox[] = boxTemplates.map((template, index) => {
  const supplier = suppliers[(index + 2) % suppliers.length];
  const price =
    template.businessType === "Bakery" ? 450 + index * 25 :
    template.businessType === "Crochet" ? 320 + index * 20 :
    template.businessType === "Jewellery" ? 640 + index * 30 :
    template.businessType === "Chocolates" ? 520 + index * 25 :
    template.businessType === "Candles" ? 480 + index * 22 :
    template.businessType === "Rakhi" ? 420 + index * 18 : 390 + index * 19;

  return {
    id: `box-${index + 1}`,
    name: template.name,
    imageUrl: getImageUrl(template.name, template.category),
    purpose: template.purpose,
    description: template.description,
    businessTypes: [template.businessType as BusinessType],
    category: template.category,
    price,
    currency: "INR",
    minimumOrderQuantity: `${30 + (index % 4) * 10} units`,
    supplier: supplier.name,
    supplierId: supplier.id,
    tags: template.tags,
    ecoFriendly: template.ecoFriendly,
    reusable: template.reusable,
    recyclable: template.recyclable,
    fragileSupport: template.name.includes("Box") || template.name.includes("Vessel"),
    waterproof: template.name.includes("Bakery") || template.name.includes("Vessel"),
    bestFor: template.bestFor,
    advantages: ["Strong structure", "Premium presentation"],
    disadvantages: template.name.includes("Jewellery") ? ["Higher cost"] : ["Requires storage space"],
    availability: index % 2 === 0 ? "In stock" : "Pre-order",
  };
});

const accessoryTemplates = [
  {
    name: "Thank You Card",
    purpose: "Customer appreciation insert",
    description: "A branded thank-you card that leaves a warm impression and strengthens repeat orders.",
    bestFor: "All businesses",
    advantages: ["Brand reinforcement", "Customer retention"],
    disadvantages: ["Adds one extra insert"],
    tags: ["brand", "thank-you"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Brand Sticker",
    purpose: "Labeling and sealing",
    description: "A compact sticker used to seal boxes and reinforce a business identity on every order.",
    bestFor: "Bakery, gifts, candles, jewellery",
    advantages: ["Cost-effective", "Brand visible"],
    disadvantages: ["Limited space"],
    tags: ["branding", "label"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Ribbon",
    purpose: "Gift finish",
    description: "A decorative ribbon used to tie package closures and elevate the presentation of gift items.",
    bestFor: "Jewellery, Rakhi, chocolates, candles",
    advantages: ["Premium touch", "Good for gifting"],
    disadvantages: ["Not a protective layer"],
    tags: ["gift", "decoration"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: true,
    recyclable: false,
  },
  {
    name: "Bakery Label",
    purpose: "Food product labeling",
    description: "A bakery label that helps identify flavours, ingredients, and day-of-bake details clearly.",
    bestFor: "Bakery, confectionery, cafe counters",
    advantages: ["Clear labeling", "Helpful for customers"],
    disadvantages: ["Requires consistent design"],
    tags: ["bakery", "label"],
    businessType: "Bakery",
    category: "Bakery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Care Instructions Card",
    purpose: "Product use guidance",
    description: "A small card that explains product handling, care steps, and material details for customers.",
    bestFor: "Crochet, jewellery, handcrafted goods",
    advantages: ["Improves care", "Helpful after purchase"],
    disadvantages: ["Additional print cost"],
    tags: ["care", "handmade"],
    businessType: "Crochet",
    category: "Craft",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Jewellery Care Card",
    purpose: "Jewellery care and cleaning guidance",
    description: "A compact care guide that tells customers how to protect and preserve jewellery after purchase.",
    bestFor: "Jewellery, luxury gifting",
    advantages: ["Value-adding", "Helpful for retention"],
    disadvantages: ["Extra card in packaging"],
    tags: ["jewellery", "care"],
    businessType: "Jewellery",
    category: "Jewellery",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Flavour Label",
    purpose: "Chocolate flavour identification",
    description: "A neat label to identify flavours, ingredients, and gifting details for chocolate assortments.",
    bestFor: "Chocolate, confectionery gifts",
    advantages: ["Clear presentation", "Brandable"],
    disadvantages: ["Needs careful print setup"],
    tags: ["chocolate", "label"],
    businessType: "Chocolates",
    category: "Chocolates",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Gift Sleeve",
    purpose: "Wrap-around card holder",
    description: "A sleeve that adds a premium finish to candle or rakhi gifts while keeping the pack compact.",
    bestFor: "Candles, Rakhi, small gifts",
    advantages: ["Compact", "Premium finish", "Low cost"],
    disadvantages: ["Less structural support"],
    tags: ["gift", "sleeve"],
    businessType: "General",
    category: "General",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Candle Care Card",
    purpose: "Burn and care instructions",
    description: "A care card that tells customers how to burn and store candles safely while extending the brand touchpoint.",
    bestFor: "Candles, gift candle sets",
    advantages: ["Useful after purchase", "Brand reinforcement"],
    disadvantages: ["Extra print item"],
    tags: ["candles", "care", "label"],
    businessType: "Candles",
    category: "Candles",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Festive Greeting Card",
    purpose: "Rakhi gifting insert",
    description: "A celebratory card used to enhance festive presentation and messaging on Rakhi gifting sets.",
    bestFor: "Rakhi, festival gifting, family orders",
    advantages: ["Festive finish", "Brandable", "High emotional appeal"],
    disadvantages: ["Adds a small extra print step"],
    tags: ["rakhi", "festival", "card"],
    businessType: "Rakhi",
    category: "Rakhi",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Clothing Care Card",
    purpose: "Care and handling guidance",
    description: "A short care card detailing wash, storage, and product handling for fashion and apparel items.",
    bestFor: "Clothing, fashion, premium apparel",
    advantages: ["Customer education", "Brandable", "Helps reduce returns"],
    disadvantages: ["Adds an extra insert"],
    tags: ["fashion", "care", "clothing"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Hang Tag",
    purpose: "Apparel branding tag",
    description: "A premium hang tag used for outfit labels, price, and brand presentation on garments.",
    bestFor: "Clothing, boutique retail, apparel gifting",
    advantages: ["Strong visibility", "Easy to brand", "Retail-ready"],
    disadvantages: ["Not a protective layer"],
    tags: ["fashion", "hang tag", "branding"],
    businessType: "Clothing",
    category: "Clothing",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Ingredient Label",
    purpose: "Handmade soap product info",
    description: "A clean ingredient and usage label to support transparency and retail presentation for soap bars.",
    bestFor: "Handmade soap, natural bar products",
    advantages: ["Informative", "Brand support", "Customer trust"],
    disadvantages: ["Needs careful print fit"],
    tags: ["soap", "label", "ingredients"],
    businessType: "Handmade Soap",
    category: "Handmade Soap",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
  {
    name: "Storage Care Card",
    purpose: "Handling guidance for soap packaging",
    description: "A compact storage and care note designed for handmade soap products that need proper drying and storage guidance.",
    bestFor: "Handmade soap, natural bath goods",
    advantages: ["Useful to customers", "Improves product care"],
    disadvantages: ["Extra print step"],
    tags: ["soap", "care", "storage"],
    businessType: "Handmade Soap",
    category: "Handmade Soap",
    ecoFriendly: true,
    reusable: false,
    recyclable: true,
  },
];

export const accessories: Accessory[] = accessoryTemplates.map((template, index) => {
  const supplier = suppliers[(index + 4) % suppliers.length];
  const price =
    template.businessType === "Bakery" ? 85 + index * 7 :
    template.businessType === "Crochet" ? 70 + index * 6 :
    template.businessType === "Jewellery" ? 100 + index * 8 :
    template.businessType === "Chocolates" ? 90 + index * 7 :
    template.businessType === "Candles" ? 80 + index * 6 :
    template.businessType === "Rakhi" ? 95 + index * 7 : 75 + index * 6;

  return {
    id: `acc-${index + 1}`,
    name: template.name,
    imageUrl: getImageUrl(template.name, template.category),
    purpose: template.purpose,
    description: template.description,
    businessTypes: [template.businessType as BusinessType],
    category: template.category,
    price,
    currency: "INR",
    minimumOrderQuantity: `${50 + (index % 4) * 10} units`,
    supplier: supplier.name,
    supplierId: supplier.id,
    tags: template.tags,
    ecoFriendly: template.ecoFriendly,
    reusable: template.reusable,
    recyclable: template.recyclable,
    fragileSupport: false,
    waterproof: template.name.includes("Label") || template.name.includes("Card"),
    bestFor: template.bestFor,
    advantages: template.advantages,
    disadvantages: template.name.includes("Ribbon") ? ["Not structurally protective"] : ["Extra item to manage"],
    availability: index % 2 === 0 ? "In stock" : "Limited",
  };
});

export const guides: PackagingGuide[] = businessTypes.map((type) => ({
  id: `guide-${type.toLowerCase().replace(/\s+/g, "-")}`,
  title: `${type} packaging guide`,
  summary: `${type} packaging should combine product protection with a premium customer experience.`,
  steps: [
    "Choose packaging based on product fragility.",
    "Use branded inserts and labels.",
    "Prioritize eco-friendly materials where possible.",
  ],
  businessType: type,
}));

export const ecoAlternatives: EcoAlternative[] = [
  { id: "ea1", name: "Recycled kraft mailer", description: "A lower-impact substitute for plastic bubble wrap.", replacementFor: "Bubble Wrap", businessType: "Crochet" },
  { id: "ea2", name: "Compostable paper tape", description: "A clean alternative to synthetic plastic tape.", replacementFor: "Plastic Tape", businessType: "Bakery" },
  { id: "ea3", name: "Soy-based ink labels", description: "A greener print finish for branded stickers.", replacementFor: "Standard labels", businessType: "Candles" },
  { id: "ea4", name: "Reusable drawstring pouch", description: "A reusable pouch that reduces waste and adds value.", replacementFor: "Single-use gift bag", businessType: "Jewellery" },
  { id: "ea5", name: "Seed paper thank-you card", description: "A card that grows into herbs when planted.", replacementFor: "Standard thank-you card", businessType: "Gift Products" },
];
